
obj-y := prom.o cmdline.o printf.o setup.o time.o irq.o

obj-$(CONFIG_PCI) += pci.o
obj-$(CONFIG_RT3XXX_EHCI_OHCI) += dev-ehci_ohci.o
obj-$(CONFIG_RALINK_TIMER_WDG) += rt_timer_wdg.o
obj-$(CONFIG_MIPS_MT_SMP) += malta-smp.o
obj-$(CONFIG_MIPS_MT_SMTC) += malta-smtc.o
